name: virok_wms
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  audioplayers: ^5.1.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_beep: ^1.0.0
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  http: ^1.1.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  pinput: ^3.0.1
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
   - assets/icons/

