name: virok_wms
description: A new Flutter project.
publish_to: 'none'
version: 2.4.2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.0.0
  ai_barcode_scanner: ^3.4.1
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  numberpicker: ^2.1.2
  path: ^1.8.3
  pinput: ^3.0.1
  shared_preferences: ^2.2.1
  adaptive_theme: ^3.4.1
  flutter_slidable: ^3.0.1
  # local_session_timeout: ^2.3.2
  package_info_plus: ^6.0.0
  animations: ^2.0.11
  barcode_widget: ^2.0.4
  pdf: ^3.11.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  flutter_beep: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/image/

