// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFqYM4c_d7ph5X0EgJbdtmlupG3Piy7SQ',
    appId: '1:527829636188:web:30aefb31a94b25ada08299',
    messagingSenderId: '527829636188',
    projectId: 'virok-wms-2a767',
    authDomain: 'virok-wms-2a767.firebaseapp.com',
    storageBucket: 'virok-wms-2a767.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ8G_OLcS7CeshV7rA4khppo9p2GRekS4',
    appId: '1:527829636188:android:cccc3d14f3beef06a08299',
    messagingSenderId: '527829636188',
    projectId: 'virok-wms-2a767',
    storageBucket: 'virok-wms-2a767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBC86qfA14nB5iUwyXsHoSnBWuAqkJzBs',
    appId: '1:527829636188:ios:987946a1d850ccc9a08299',
    messagingSenderId: '527829636188',
    projectId: 'virok-wms-2a767',
    storageBucket: 'virok-wms-2a767.appspot.com',
    iosBundleId: 'com.dtLogic.virokwms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBC86qfA14nB5iUwyXsHoSnBWuAqkJzBs',
    appId: '1:527829636188:ios:6b475e26f7a3b0b6a08299',
    messagingSenderId: '527829636188',
    projectId: 'virok-wms-2a767',
    storageBucket: 'virok-wms-2a767.appspot.com',
    iosBundleId: 'com.example.virokVms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFqYM4c_d7ph5X0EgJbdtmlupG3Piy7SQ',
    appId: '1:527829636188:web:30aefb31a94b25ada08299',
    messagingSenderId: '527829636188',
    projectId: 'virok-wms-2a767',
    authDomain: 'virok-wms-2a767.firebaseapp.com',
    storageBucket: 'virok-wms-2a767.appspot.com',
  );
}
